import { ApplicationConfig, importProvidersFrom, provideZoneChangeDetection } from '@angular/core';
import { provideRouter, withComponentInputBinding, withRouterConfig } from '@angular/router';
import { routes } from './app.routes';
import { providePrimeNG } from 'primeng/config';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { BrowserAnimationsModule, provideAnimations } from '@angular/platform-browser/animations'; // IMPORTAR
import Aura from '@primeng/themes/aura';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { jwtInterceptor } from './core/auth/jwt.interceptor';

export const appConfig: ApplicationConfig = {
  providers: [
  
    provideAnimationsAsync(),
    providePrimeNG({
      theme: {
        preset: Aura,
        options: {
          darkModeSelector: ".p-dark",
          cssLayer: {
            name: "primeng",
            order: "theme, base, primeng",
          },
        },
      },
      ripple: true,
      zIndex: {
        modal: 1100, // dialog, sidebar
        overlay: 1000, // dropdown, overlaypanel
        menu: 1000, // overlay menus
        tooltip: 1100, // tooltip
      },
      translation: {
          accept: "Sim",
          addRule: "Adicionar Regra",
          am: "AM",
          apply: "Aplicar",
          cancel: "Cancelar",
          choose: "Escolher",
          chooseDate: "Escolher Data",
          chooseMonth: "Escolher Mês",
          chooseYear: "Escolher Ano",
          clear: "Limpar",
          contains: "Contém",
          dateAfter: "Data depois de",
          dateBefore: "Data antes de",
          dateFormat: "dd/mm/yy",
          dateIs: "Data é",
          dateIsNot: "Data não é",
          dayNames: [
            "Domingo",
            "Segunda-feira",
            "Terça-feira",
            "Quarta-feira",
            "Quinta-feira",
            "Sexta-feira",
            "Sábado",
          ],
          dayNamesMin: ["D", "S", "T", "Q", "Q", "S", "S"],
          dayNamesShort: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
          emptyFilterMessage: "Nenhum resultado encontrado",
          emptyMessage: "Nenhuma opção disponível",
          emptySearchMessage: "Nenhum resultado encontrado",
          emptySelectionMessage: "Nenhum item selecionado",
          endsWith: "Termina com",
          equals: "Igual",
          fileChosenMessage: "{0} arquivos",
          fileSizeTypes: ["B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB"],
          firstDayOfWeek: 0,
          gt: "Maior que",
          gte: "Maior ou igual a",
          lt: "Menor que",
          lte: "Menor ou igual a",
          matchAll: "Corresponder Todos",
          matchAny: "Corresponder Qualquer",
          medium: "Médio",
          monthNames: [
            "Janeiro",
            "Fevereiro",
            "Março",
            "Abril",
            "Maio",
            "Junho",
            "Julho",
            "Agosto",
            "Setembro",
            "Outubro",
            "Novembro",
            "Dezembro",
          ],
          monthNamesShort: [
            "Jan",
            "Fev",
            "Mar",
            "Abr",
            "Mai",
            "Jun",
            "Jul",
            "Ago",
            "Set",
            "Out",
            "Nov",
            "Dez",
          ],
          nextDecade: "Próxima Década",
          nextHour: "Próxima Hora",
          nextMinute: "Próximo Minuto",
          nextMonth: "Próximo Mês",
          nextSecond: "Próximo Segundo",
          nextYear: "Próximo Ano",
          noFileChosenMessage: "Nenhum arquivo escolhido",
          noFilter: "Sem Filtro",
          notContains: "Não contém",
          notEquals: "Diferente",
          passwordPrompt: "Digite uma senha",
          pending: "Pendente",
          pm: "PM",
          prevDecade: "Década Anterior",
          prevHour: "Hora Anterior",
          prevMinute: "Minuto Anterior",
          prevMonth: "Mês Anterior",
          prevSecond: "Segundo Anterior",
          prevYear: "Ano Anterior",
          reject: "Não",
          removeRule: "Remover Regra",
          searchMessage: "Existem {0} resultados disponíveis",
          selectionMessage: "{0} itens selecionados",
          startsWith: "Começa com",
          strong: "Forte",
          today: "Hoje",
          upload: "Enviar",
          weak: "Fraco",
          weekHeader: "Sem",
          aria: {
            cancelEdit: "Cancelar Edição",
            close: "Fechar",
            collapseRow: "Recolher Linha",
            editRow: "Editar Linha",
            expandRow: "Expandir Linha",
            falseLabel: "Falso",
            filterConstraint: "Restrição de Filtro",
            filterOperator: "Operador de Filtro",
            firstPageLabel: "Primeira Página",
            gridView: "Visualização de Grade",
            hideFilterMenu: "Esconder Menu de Filtro",
            jumpToPageDropdownLabel: "Ir para a Página",
            jumpToPageInputLabel: "Ir para a Página",
            lastPageLabel: "Última Página",
            listLabel: "Lista de opções",
            listView: "Visualização de Lista",
            moveAllToSource: "Mover Todos para a Origem",
            moveAllToTarget: "Mover Todos para o Destino",
            moveBottom: "Mover para o Final",
            moveDown: "Mover para Baixo",
            moveTop: "Mover para o Topo",
            moveToSource: "Mover para a Origem",
            moveToTarget: "Mover para o Destino",
            moveUp: "Mover para Cima",
            navigation: "Navegação",
            next: "Próximo",
            nextPageLabel: "Próxima Página",
            nullLabel: "Não Selecionado",
            pageLabel: "Página {page}",
            previous: "Anterior",
            prevPageLabel: "Página Anterior",
            removeLabel: "Remover",
            rotateLeft: "Rotacionar para a Esquerda",
            rotateRight: "Rotacionar para a Direita",
            rowsPerPageLabel: "Linhas por página",
            saveEdit: "Salvar Edição",
            scrollTop: "Rolar para o Topo",
            selectAll: "Todos os itens selecionados",
            selectRow: "Linha Selecionada",
            showFilterMenu: "Mostrar Menu de Filtro",
            slide: "Deslizar",
            slideNumber: "Slide {slideNumber}",
            star: "1 estrela",
            stars: "{star} estrelas",
            trueLabel: "Verdadeiro",
            unselectAll: "Todos os itens desmarcados",
            unselectRow: "Linha Desmarcada",
            zoomImage: "Ampliar Imagem",
            zoomIn: "Ampliar",
            zoomOut: "Reduzir",
          },
      },
    }),
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes, withComponentInputBinding()),
    provideHttpClient(withInterceptors([jwtInterceptor])),
  ],
};
